### ISSUE TITLE
[rlevo-benchmarks] tui/record/report builds without json fail clippy (E0432 + dead imports, not covered by #391)

### ISSUE THREAD

**Issue by anthonytorlucci** [anthonytorlucci/rlevo#1039]
## What

Three `rlevo-benchmarks` feature combinations fail `cargo clippy --all-targets ... -- -D warnings` when the crate is built **without** its `json` feature. Found while resolving #405 (removal of the `serde` supertrait from `Observation<R>`).

This is **not** covered by #391. #391 (closed) is about four production crates missing the `[lints] workspace = true` opt-in; `rlevo-benchmarks` already has it (`crates/rlevo-benchmarks/Cargo.toml`, last line). The failure here is a hard `E0432 unresolved import` from a missing optional dependency plus genuine dead-import warnings — neither is something a lint-table change can touch. `[lints] workspace = true` only decides which lints run; it cannot supply a crate that isn't linked.

## Reproducer

All commands run with `cargo clean -p rlevo-benchmarks` first (the failures are default-feature-shadowed — see below — so a warm target dir from a default build hides them).

```
$ cargo clippy -p rlevo-benchmarks --all-targets --no-default-features --features tui -- -D warnings
```
5 errors: `E0432 unresolved import 'serde'` at `env_wrappers/tui_env_tap.rs:204`, plus 4 cascading `E0277` ("the trait bound `StubObs: serde::Serialize`/`Deserialize` is not satisfied") from `Observation`'s (pre-#405) serde supertrait.

With the #405 diff applied (`Observation<R>: Debug + Clone + Send + Sync`, no serde supertrait), the 4 `E0277`s disappear and only the 1 `E0432` remains — confirming the supertrait was an amplifier here, not the origin. #405 does not fix this issue; it only removes the amplified half.

```
$ cargo clippy -p rlevo-benchmarks --all-targets --no-default-features --features record -- -D warnings
$ cargo clippy -p rlevo-benchmarks --all-targets --no-default-features --features report -- -D warnings
```
Both: 2 errors in `tests/wire_format_compat.rs` — `unused imports: CheckpointFormat as NativeCheckpointFormat, CheckpointKind as NativeCheckpointKind, CheckpointRef as NativeCheckpointRef, and RunManifest as NativeManifest` (line 16) and `unused import: rlevo_core::objective::ObjectiveSense as NativeObjectiveSense` (line 28). Unaffected by #405 (unrelated to `Observation`).

```
$ cargo clippy -p rlevo-benchmarks --all-targets --all-features -- -D warnings          # clean
$ cargo clippy -p rlevo-benchmarks --all-targets --no-default-features -- -D warnings   # clean
```
Both pass. `--all-features` links `serde` via `json`/`record`/`report` regardless of `tui`; `wire_format_compat.rs` is `#![cfg(feature = "record")]`-gated so it doesn't build at all without `record`. This is why the isolated-feature failures went unnoticed: the two configurations anyone runs by habit both happen to route around the gap.

**Also note:** the literal command `cargo clippy -p rlevo-benchmarks --all-targets --features tui -- -D warnings` (default features left on) is clean too — `tui` alone with the crate's `default = ["json"]` still links serde through `json`. The failure requires `--no-default-features --features tui` specifically; the reproducer above is the accurate one.

## Root cause

`crates/rlevo-benchmarks/Cargo.toml` `[features]`:
```
default = ["json"]
json = ["dep:serde", "dep:serde_json"]
tui = ["dep:ratatui", "dep:crossterm", "dep:tracing-subscriber"]
record = ["dep:bincode", "dep:parking_lot", "dep:toml", "dep:time", "dep:serde", "dep:tracing-subscriber", "dep:rlevo-evolution"]
report = ["record", "dep:base64", "dep:serde_json"]
```

1. **`tui` / E0432** — `crates/rlevo-benchmarks/src/env_wrappers/tui_env_tap.rs:204` (`#[cfg(test)] mod tests`) has an unconditional `use serde::{Deserialize, Serialize};` and derives `Serialize, Deserialize` on the local `StubObs` (line 210) so it satisfies `Observation`'s (pre-#405) serde supertrait. `tui` doesn't declare `dep:serde` and nothing else in the `tui`-only build path pulls it in. With #405 landed, `Observation<R>` no longer requires `Serialize`/`Deserialize` at all, so the derive and the import are simply unneeded — the fix is to delete them from the test stub, not to add `dep:serde` to `tui`.

2. **`record`/`report` dead imports** — `crates/rlevo-benchmarks/tests/wire_format_compat.rs:16-24,28` import `NativeManifest`/`NativeCheckpoint*`/`NativeObjectiveSense` unconditionally at file scope, but the only place that uses them, the test function at line 363, is `#[cfg(feature = "json")]`. `record` does not imply `json` (see table above), so a `--features record` (or `report`, which enables `record`) build without `json` compiles the imports and never consumes them. Fix: gate the imports at lines 16-24 and 28 on `feature = "json"` too (or move them inside the gated `fn`).

## Why CI never caught it

`.github/workflows/crate-tests.yml`'s `test` matrix runs `cargo test -p rlevo-benchmarks` with default features (`json` on) — no clippy, no `-D warnings`, and `json` masks both bugs anyway. The only job in this repo that runs `clippy --all-targets --no-default-features --features <X>` in isolation is `feature-orthogonality` (`crate-tests.yml:127-146`), and it is scoped to `rlevo-environments`'s `box2d`/`locomotion` pair only. No workflow exercises `rlevo-benchmarks`'s `tui`/`record`/`report` features against `--no-default-features`, so nothing in CI could have found this.

## Scope note

Confirmed **not** duplicative of #391: `rlevo-benchmarks` is outside #391's four-crate list and already carries `[lints] workspace = true`; these are dependency-declaration and dead-import bugs in the crate's own source, orthogonal to whether the workspace lint table is wired in.

**Comment by anthonytorlucci** [comment]
**Half of this is now fixed on the `405-core-observations-serde-bound` branch (#405).** Recording which half, and why the other half is untouched.

### Fixed: the `tui` `E0432`

The unresolved `serde` import at `crates/rlevo-benchmarks/src/env_wrappers/tui_env_tap.rs:204` existed only because the removed `Observation<R>` serde supertrait (ADR 0064) forced the test stub `StubObs` to derive `Serialize`/`Deserialize`. With the supertrait gone, the derive is dead code, and `StubObs` is a private test stub rather than public API — so ADR 0064's "retain every serde derive" rule, which exists to protect downstream `serde_json::to_string(&concrete_obs)` calls, does not cover it. Verified nothing in that test module serializes `StubObs` (it is only constructed and compared), then deleted the import and both derives.

Executed evidence:

```
cargo clippy -p rlevo-benchmarks --all-targets --no-default-features --features tui -- -D warnings
# before: 1 error — E0432 unresolved import `serde` at tui_env_tap.rs:204
# after:  0 errors — Finished dev profile
```

For the record, on the base commit this combination reported **5** errors: the `E0432` plus four `E0277`s from the serde supertrait itself. #405 removed those four; this change removes the fifth.

### Still open: the `record` / `report` dead imports

`crates/rlevo-benchmarks/tests/wire_format_compat.rs:16-24,28` imports at file scope what only a `#[cfg(feature = "json")]`-gated test at :363 consumes, so `--no-default-features --features record` and `--features report` still fail `-D warnings` with 2 unused-import errors each. That has nothing to do with the serde supertrait and was deliberately left alone — it belongs to this issue on its own terms.

### One claim in the original report I could not substantiate

The engineer who fixed the `tui` half did not sweep the remaining feature combinations, so the accurate statement is "the `tui` combination is clean now," **not** "`tui` was the only masked combination." The root cause here is structural — features that don't pull `dep:serde`, and unconditional imports consumed only under a gate — so there is no reason to assume two instances exhaust it. Whoever closes this should enumerate the combos rather than trusting that count.

The generalizable lesson stands unchanged: `--all-features` and `--no-default-features` both pass, and `crate-tests.yml` runs `rlevo-benchmarks` with default features only, so CI could not have caught any of this.
